# Generated by Django 5.2.8 on 2025-12-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_community_options_communitypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='community_banners/'),
        ),
        migrations.AddField(
            model_name='community',
            name='community_image',
            field=models.ImageField(blank=True, null=True, upload_to='community_images/'),
        ),
        migrations.AddField(
            model_name='community',
            name='rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='community',
            name='weekly_contributions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='community',
            name='weekly_visits',
            field=models.IntegerField(default=0),
        ),
    ]
