# Generated by Django 5.2.8 on 2025-12-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommend", "0002_userinterests"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinterests",
            old_name="categories",
            new_name="blog_tags",
        ),
        migrations.RenameField(
            model_name="userinterests",
            old_name="completed_onboarding",
            new_name="completed_blog_onboarding",
        ),
        migrations.AddField(
            model_name="userinterests",
            name="community_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userinterests",
            name="completed_community_onboarding",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userinterests",
            name="completed_game_onboarding",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userinterests",
            name="game_categories",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
