# Generated by Django 4.2.27 on 2025-12-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_rename_categories_userinterests_blog_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='action',
            field=models.CharField(choices=[('play', 'Play'), ('like', 'Like'), ('dislike', 'Dislike'), ('view', 'View'), ('complete', 'Complete'), ('skip', 'Skip')], default='play', max_length=20),
        ),
    ]
