# Generated by Django 4.2.16 on 2025-12-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_alter_interaction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='action',
            field=models.CharField(choices=[('play', 'Play'), ('like', 'Like'), ('dislike', 'Dislike'), ('view', 'View'), ('complete', 'Complete'), ('skip', 'Skip'), ('impression', 'Impression'), ('click', 'Click')], default='play', max_length=20),
        ),
    ]
