# Generated by Django 5.2.8 on 2025-12-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_alter_interaction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
