# Generated by Django 5.2.8 on 2025-12-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_subscription_community'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Community',
        ),
    ]
