# Generated by Django 5.2.8 on 2025-12-13 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="game_id",
        ),
        migrations.AddField(
            model_name="project",
            name="project_id",
            field=models.UUIDField(
                blank=True,
                db_column="game_id",
                help_text="UUID of the associated content from other apps",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("action", "Action"),
                    ("puzzle", "Puzzle"),
                    ("strategy", "Strategy"),
                    ("arcade", "Arcade"),
                    ("adventure", "Adventure"),
                    ("educational", "Educational"),
                    ("template", "Template"),
                    ("asset_pack", "Asset Pack"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_file",
            field=models.FileField(
                help_text="Project bundle from creator",
                upload_to="marketplace/projects/%Y/%m/",
                validators=[django.core.validators.FileExtensionValidator(["zip"])],
            ),
        ),
    ]
