# Generated by Django 5.2.8 on 2025-12-06 16:48

from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="color",
            field=models.CharField(default=accounts.models.random_color, max_length=20),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
