# Generated by Django 5.2.8 on 2025-12-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_saved_communities'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_public_socials',
            field=models.BooleanField(default=True),
        ),
    ]
