# Generated by Django 5.2.8 on 2025-12-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_lettersetgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettersetgame',
            name='letters',
            field=models.CharField(max_length=15),
        ),
    ]
