# Generated by Django 5.2.8 on 2025-12-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_gamelobbychallenge_wordlistgame"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamelobbychallenge",
            old_name="used_words",
            new_name="letters",
        ),
        migrations.RenameField(
            model_name="gamelobbychallenge",
            old_name="words",
            new_name="used_letters",
        ),
    ]
