# Generated by Django 5.2.8 on 2025-12-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_public_profile_default_false"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="allow_dms",
            field=models.BooleanField(default=True),
        ),
    ]
