# Generated by Django 5.2.8 on 2025-12-10 23:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="blocked_users",
            field=models.ManyToManyField(
                blank=True, related_name="blocked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
