# Generated by Django 5.2.8 on 2025-12-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_customuser_blocked_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                default="light",
                max_length=10,
            ),
        ),
    ]
