# Generated by Django 6.0 on 2025-12-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_customuser_theme_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="accent_color",
            field=models.CharField(default="#1f9cee", max_length=9),
        ),
        migrations.AddField(
            model_name="customuser",
            name="font_size",
            field=models.PositiveSmallIntegerField(default=14),
        ),
    ]
