# Generated by Django 4.2.16 on 2025-12-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_badge_userstats_userbadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
