# Generated by Django 5.2.8 on 2025-12-08 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment_dislikes_comment_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="likes",
        ),
        migrations.AddField(
            model_name="comment",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True,
                related_name="disliked_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
