# Generated by Django 5.2.8 on 2025-12-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_comment_dislikes_remove_comment_likes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="followers",
        ),
    ]
