# Generated by Django 5.2.8 on 2025-12-10 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationreport",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="blog.post",
            ),
        ),
    ]
